In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [6]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [7]:
flat = arr.flatten() #Reduces multi dimensional array to one dimension


In [8]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [14]:
b=flat[3:7] #we are creating a b array from  flat elements using slicing

In [15]:
b

array([444444,      5,      6,      7])

In [16]:
b[0]=444444 #we are changing element of b

In [17]:
b

array([444444,      5,      6,      7])

In [18]:
flat # here we see that flat array also changes as we make change in b array that shows that changes in flatten array affects the original too

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [19]:
mask = arr>3 #to get specific elements based on condition

In [20]:
print(arr[mask])

[ 4  5  6  7  8  9 11 12 13]
