In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#summing along axes
#axis=0 -> rows
#axis=1 -> columns
np.sum(arr,axis=0)#1+4+7=12 ... 


array([12, 15, 18])

In [9]:
np.sum(arr,axis=1) #1+2+3=6 ...

array([ 6, 15, 24])

In [11]:
arr[0][2]

np.int64(3)

In [12]:
arr[0,1]

np.int64(2)

In [13]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])