In [1]:
!pip install numpy

In [2]:
import numpy as np


In [3]:
arr=np.array([1,3,4])

In [4]:
arr


array([1, 3, 4])

In [7]:
arr1 = np.array([1,2,3]) #creating 1d array
arr2 = np.array([[1,2,3],[4,5,6]]) #creating 2d array
print ("arr1:",arr1)
print ("arr2:",arr2)

arr1: [1 2 3]
arr2: [[1 2 3]
 [4 5 6]]


In [8]:
np.zeros((3, 3))    # 3x3 array of zeros
np.ones((2, 4))     # 2x4 array of ones
np.full((2, 2), 7)  # 2x2 array filled with 7
np.eye(4)           # 4x4 identity matrix
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

NameError: name 'array' is not defined

In [10]:
np.full((2, 2), 7)  # 2x2 array filled with 7

array([[7, 7],
       [7, 7]])

In [11]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [12]:
myarr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [13]:
myarr.size #number of elements

12

In [14]:
myarr.ndim #dimensions

2

In [15]:
myarr.dtype

dtype('int64')